### ISSUE TITLE
User can view product detail

### ISSUE THREAD

**Issue by kimberly-bird** [elated-egrets/bangazon-internal-site-2.0#10]
- [x] **Given** user is viewing any page that contains a hyperlink for a product
**When** user performs a gesture on the product hyperlink
**Then** user will be shows the product detail page containing title, description, quantity available,  price/unit, and a button labeled *Add to Order*

**Comment by RileyMathews** [comment]
What needs to happen when we click the button labeled 'add to order'? where should the user be redirected to?
