### ISSUE TITLE
User can upload a photo of the product

### ISSUE THREAD

**Issue by kimberly-bird** [elated-egrets/bangazon-internal-site-2.0#11]
**Given** the user is uploading a product
**When** the user clicks "upload photo"
**And** selects a file
**Then** a thumbnail of the image will show in the Product Detail view

**Comment by Ryoung27** [comment]
Can we link the photo in the API?

**Comment by RileyMathews** [comment]
What does this look like? are we storing the pictures in the projects file structure on 'upload'?
