### ISSUE TITLE
User can remove a product listing

### ISSUE THREAD

**Issue by kimberly-bird** [elated-egrets/bangazon-internal-site-2.0#16]
- [x] **Given** the user is authenticated
**When** the user clicks on the *My Products* hyperlink in the navigation bar
**Then** the user will be presented with a list of products they (s)he has posted for sale

- [x] **Given** the list of products is presented to the user
**When** the user clicks the *Delete* button next to a posted product
**Then** the product for sale is removed from the system

**Comment by RileyMathews** [comment]
Should this be a safedelete model as well? what happens to a deleted product that was on a order that another customer wants to view in their history?

**Comment by Levi-Schubert** [comment]
if products are safe delete since they can referenced by entries that have a fk to the deleted products, will this cause issues with unfinished orders being able to order a delisted product?
