### ISSUE TITLE
User can view all product categories

### ISSUE THREAD

**Issue by kimberly-bird** [elated-egrets/bangazon-internal-site-2.0#8]
**Given** a user is viewing any page on the Bangazon site
**When** the user performs a gesture on the *Product Categories* hyperlink
- [x] **Then** the user will see a view containing a list of all product categories 
- [x] **And** next to the category name, the number of products in that category will be displayed
- [x] **And** the first three products in the category will be displayed beneath each category.
- [x] **And** the products listed are hyperlinks to the product detail

##### Sample

```
Electronics (15)
    Dryer
    HD Television
    Sony Walkman

Sporting Goods (7)
    Football
    Ice skates
    Basketball hoop
```

**Comment by RileyMathews** [comment]
once again. is the product categories hyperlink a navbar item?

**Comment by Levi-Schubert** [comment]
as per Gregs instruction users should also be able to add a category

**Comment by Levi-Schubert** [comment]
on the multi category view, each category should hyperlink to a detail view for the category that lists all the products associated
